version: '3.9'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
